baseURL = "http://hugosite.angelabennedsen.dk/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"

[[menu.main]]
name                   = "Home"
weight                 = 1
identifier             = "home"
url                    = "/home/"

[[menu.main]]
name                   = "About"
weight                 = 2
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Contact"
weight                 = 3
identifier             = "contact"
url                    = "/contact/"

[[menu.main]]
name                   = "Blog"
weight                 = 4
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Portfolio"
weight                 = 5
identifier             = "portfolio"
url                    = "/portfolio/"

[params]
extracssfiles          = [ "/css/override.css" ]